---
title: "Analyse de biomasse sous gradient de CO2"
author: "Océane"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    df_print: paged
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE )
library(tidyverse)
library(splines)
library(ggpubr)
library(jsonlite)
```


# Contexte



# Visualisation des données

```{r, fig.width=10, fig.height=8}
data <- read.csv("../data/OC_08_dry_biomass.csv", sep=';')
annot <- read.csv("../data/OC_08_annotation.csv", sep=';')

DF=4

data <- data %>%
  filter(!str_detect(TubeVide, "Date")) %>%
  mutate(Dry_mass_mg = (parse_number(Tube_masse_seche)- parse_number(TubeVide))*1000) %>%
  select(Tube, Dry_mass_mg) %>% 
  inner_join(annot, by="Tube") %>%
  select(-c(Tissue, RNA)) %>%
  filter(Dry_mass_mg >0)

data %>%
  ggplot(aes(x=CO2, y=Dry_mass_mg, color=N, fill=N))+
  geom_smooth(method = "lm", se = T, size = 1, alpha=0.3,
              formula = y ~ ns(x, df=DF))+
  geom_boxplot(aes(group=interaction(CO2, N), color=N), 
               alpha=1, width=20, fill="white", outlier.alpha = 0)+
  geom_dotplot(aes(group=interaction(CO2, N)),
               binaxis='y', stackdir='center', dotsize = 0.35)+ 
  theme_pubr() + 
  scale_color_brewer(palette = "Accent") + 
  scale_fill_brewer(palette = "Accent") + 
  ylab("Dry biomass (mg)") +
  ggtitle("Dry biomass of plants under CO2 gradient and 2 types of N nutrition")+
  xlim(c(390, 910)) +
  labs(subtitle = "Spline interpolation, N=11 or 12 per CO2*N condition")
```

# Régression par splines

```{r}
data %>%
  lm(formula=Dry_mass_mg ~ ns(CO2, df=DF)*N)%>%
  summary()
```


```{r}
data.frame(ns(data$CO2, df=DF)) %>%
  mutate(CO2 = data$CO2) %>%
  gather(key="DF", value = "Value", contains("X")) %>%
  ggplot(aes(x=CO2, y=Value, color=DF))+
  geom_point() + geom_smooth() + theme_pubr()
```



